### ISSUE TITLE
Trouble "Getting Started" with crra

### ISSUE THREAD

**Issue by charlieroth** [knowbody/crra#47]
So here is a screenshot of the errors that is outputted after only running `yarn start`:

<img width="853" alt="screen shot 2017-07-27 at 12 23 16 am" src="https://user-images.githubusercontent.com/13981427/28654481-9f832af4-7262-11e7-98f7-a5e5f9c807ba.png">

Being a complete beginner with reason/reason-react, is there anyway I can get some help with solving these errors?

**Comment by knowbody** [comment]
what version of node are you using?

**Comment by charlieroth** [comment]
8.1.4 @knowbody

**Comment by pikelnys** [comment]
@knowbody I'm getting the same error.

When I initially run `yarn start` I get the following webpack error: 
```
ERROR in multi webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./lib/js/src/index.js
Module not found: Error: Can't resolve './lib/js/src/index.js' in '/Users/stevepikelny/Desktop/code/test/totally-reasonable'
 @ multi webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./lib/js/src/index.js
```
But I think the failure is missing some clean up.

If I run `yarn start` a second time, I get the error related to the port being in use.

**Comment by makadaw** [comment]
Hi, Get the same error also.
Node version 8.2.1
```bash
   ______                __          ____                                 ____                  __     ___
  / ____/_______  ____ _/ /____     / __ \___  ____ __________  ____     / __ \___  ____ ______/ /_   /   |  ____  ____
 / /   / ___/ _ \/ __ `/ __/ _ \   / /_/ / _ \/ __ `/ ___/ __ \/ __ \   / /_/ / _ \/ __ `/ ___/ __/  / /| | / __ \/ __ \
/ /___/ /  /  __/ /_/ / /_/  __/  / _, _/  __/ /_/ (__  ) /_/ / / / /  / _, _/  __/ /_/ / /__/ /_   / ___ |/ /_/ / /_/ /
\____/_/   \___/\__,_/\__/\___/  /_/ |_|\___/\__,_/____/\____/_/ /_/  /_/ |_|\___/\__,_/\___/\__/  /_/  |_/ .___/ .___/
                                                                                                         /_/   /_/
Serving your content at localhost:8080

[BUCKLESCRIPT]
Compiling...

[WEBPACK]
Compiling...events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at Server.listen (net.js:1467:7)
    at Server.listen (/Users/MainUser/Projects/TrackMyCent/node_modules/webpack-dev-server/lib/Server.js:483:47)
    at Object.<anonymous> (/Users/MainUser/Projects/TrackMyCent/scripts/webpackDevServer.js:25:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

error Command failed with exit code 1.
```
When I run `yarn run build` get other error:
```
[1/3] Building src/app.cmj /Users/.../lib/js/src/app.js src/app.cmi
FAILED: src/app.cmj /Users/.../lib/js/src/app.js src/app.cmi
/Users/.../node_modules/bs-platform/bin/bsc.exe -bs-package-name create-reason-react-app  -bs-package-output commonjs:lib/js/src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include -I /Users/.../node_modules/reason-react/lib/ocaml -I /Users/.../node_modules/bs-director/lib/ocaml -I src  -nostdlib -I '/Users/.../node_modules/bs-platform/lib/ocaml' -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -o src/app.mlast -c  src/app.mlast && /Users/..././scripts/copy.js /Users/MainUser/Projects/TrackMyCent/lib/js/src/app.js
File "/Users/.../src/app.re", line 7, characters 14-16:
Error: This pattern matches values of type unit
       but a pattern was expected which matches values of type
         ('a, 'b) ReasonReact.self
```
Here is how line 7 looks like
```reason
render: fun () self =>
```

**Comment by dardub** [comment]
With node 8 I am getting the same error. But with node 7 there is no error, but I'm not able to connect to the server using localhost:8080.

**Comment by persianturtle** [comment]
I am using Node v7.9.0 and crra v0.2.3 and am facing the same problems.

`Error: listen EADDRINUSE :::8080`

Then when running `killall -9 node`, and re-running `yarn start`:

```
ERROR in multi webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./lib/js/src/index.js
Module not found: Error: Can't resolve './lib/js/src/index.js' in '/Users/raphael.rafatpanah/Code/reason/create'
 @ multi webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./lib/js/src/index.js
```

And when running `yarn build`:

```
File "/Users/raphael.rafatpanah/Code/reason/create/src/app.re", line 7, characters 14-16:
Error: This pattern matches values of type unit
       but a pattern was expected which matches values of type
         ('a, 'b) ReasonReact.self
ninja: build stopped: subcommand failed.
```

**Comment by Connorelsea** [comment]
I am getting the same problem. I am running node 8.0.0. Using `npm start`

**Comment by chenglou** [comment]
Hello! This repo is deprecated in favor of the create-react-app extension we've made, documented here: https://reasonml.github.io/reason-react/gettingStarted.html#getting-started-reason-scripts

I'll close this issue and put up a deprecation warning so that people don't accidentally install this anymore. Sorry for the trouble!
